language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules

jobs:
  include:
      - stage: Produce Coverage
        node_js: node
        script: npm run test -- --watchAll=false --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage  